quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:${QUARKUS_DATASOURCE_PASSWORD:1625}}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/fluxplay}

quarkus.http.cors.enabled=true
quarkus.http.cors.methods=GET, POST, PUT, PATCH, DELETE, OPTIONS
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.headers=Content-Type, Authorization

quarkus.hibernate-orm.schema.management.strategy=${HIBERNATE_SCHEMA_STRATEGY:validate}
quarkus.hibernate-orm.log.sql=${HIBERNATE_LOG_SQL:true}

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.validate-on-migrate=false

quarkus.oidc.auth-server-url=http://localhost:8080/realms/fluxplay
quarkus.oidc.client-id=fluxplay-api
quarkus.oidc.credentials.secret=${KEYCLOAK_SECRET:qhidY98rq2IEVEfIsXR2s8AmN5kYB5HO}
quarkus.oidc.application-type=service

quarkus.http.port=${HTTP_PORT:8081}